# _config.yml

# Site settings
title: Puneet Walia
description: A portfolio website for showcasing my projects and resume.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


